# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.uic import *
from PyQt5.QtWidgets import *
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_loginpage(object):
    def openWindow(self, loginpage):
        from signup import Ui_signup_2
        loginpage.close()
        self.win = QtWidgets.QMainWindow()
        self.ui = Ui_signup_2()
        self.ui.setupUi(self.win)
        self.win.show()

    def openWindow2(self, loginpage):
        from task import Ui_addtask
        loginpage.close()
        self.win = QtWidgets.QMainWindow()
        self.ui = Ui_addtask()
        self.ui.setupUi(self.win)
        self.win.show()

    def handlelogin(self):
        try:
            # connecting db
            connect = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="task manager"
            )
            base = connect.cursor()

            # getting info
            username = self.username.text()
            password = self.password.text()

            # verifying values
            if not username or not password:
                QMessageBox.critical(self.win, "Error", "You should insert all values")
                return

            # checking account
            base.execute("SELECT * FROM compte WHERE username = %s AND password = %s ", (username, password))
            result = base.fetchall()

            if len(result) == 1:
                QMessageBox.information(self.win, "Success", "Login successful")
                self.result = True
            else:
                QMessageBox.critical(self.win, "Error", "Check your login info")
                self.result = False
        except mysql.connector.Error as error:
            print(error)
        finally:
            if connect.is_connected():
                base.close()
                connect.close()

        # Save username to a file
        with open("storage.txt", "w") as f:
            f.write(username)

    def handle_login_clicked(self):
        if self.result:
            self.openWindow2(self.win)
    def setupUi(self, loginpage):
        global result
        self.win = loginpage
        loginpage.setObjectName("login page")
        loginpage.resize(890, 611)
        loginpage.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(loginpage)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 20, 621, 521))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(260, 10, 321, 61))
        self.label.setMinimumSize(QtCore.QSize(321, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 170, 255);")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 101, 41))
        self.label_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(self.widget)
        self.username.setGeometry(QtCore.QRect(200, 150, 261, 31))
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(110, 240, 101, 41))
        self.label_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(200, 270, 261, 31))
        self.password.setObjectName("password")
        self.login = QtWidgets.QPushButton(self.widget)
        self.login.setGeometry(QtCore.QRect(260, 360, 111, 51))
        self.login.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.login.setObjectName("login")
        self.login.clicked.connect(lambda: self.handlelogin())

        self.login.clicked.connect(lambda: self.handle_login_clicked())


        self.redsignup = QtWidgets.QPushButton(self.widget)
        self.redsignup.setGeometry(QtCore.QRect(260, 450, 111, 31))
        self.redsignup.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.redsignup.setObjectName("redsignup")

        self.redsignup.clicked.connect(lambda: self.openWindow(loginpage))#________________________

        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(310, 420, 31, 21))
        self.label_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_4.setObjectName("label_4")
        self.signin_3 = QtWidgets.QPushButton(self.widget)
        self.signin_3.setGeometry(QtCore.QRect(500, 480, 111, 31))
        self.signin_3.setStyleSheet("background-color: lightblue ;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: black;")
        self.signin_3.setObjectName("signin_3")
        loginpage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(loginpage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName("menubar")
        self.menulogin = QtWidgets.QMenu(self.menubar)
        self.menulogin.setObjectName("menulogin")
        loginpage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(loginpage)
        self.statusbar.setObjectName("statusbar")
        loginpage.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menulogin.menuAction())

        self.retranslateUi(loginpage)
        self.signin_3.clicked.connect(loginpage.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(loginpage)

    def retranslateUi(self, loginpage):
        _translate = QtCore.QCoreApplication.translate
        loginpage.setWindowTitle(_translate("loginpage", "MainWindow"))
        self.label.setWhatsThis(_translate("loginpage", "<html><head/><body><p align=\"justify\"><span style=\" font-size:22pt;\"><br/></span></p></body></html>"))
        self.label.setText(_translate("loginpage", "Login"))
        self.label_2.setText(_translate("loginpage", "username :"))
        self.label_3.setText(_translate("loginpage", "password :"))
        self.login.setText(_translate("loginpage", "Sign In"))
        self.redsignup.setText(_translate("loginpage", "Sign Up"))
        self.label_4.setText(_translate("loginpage", "Or"))
        self.signin_3.setText(_translate("loginpage", "Close"))
        self.menulogin.setTitle(_translate("loginpage", "login"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginpage = QtWidgets.QMainWindow()
    ui = Ui_loginpage()
    ui.setupUi(loginpage)
    loginpage.show()
    sys.exit(app.exec_())
