# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import *
from PyQt5.QtWidgets import *
import mysql.connector

class Ui_signup_2(object):

    def openWindow(self , signup_2):
        from login import Ui_loginpage
        signup_2.close()
        self.win = QtWidgets.QMainWindow()
        self.ui = Ui_loginpage()
        self.ui.setupUi(self.win)
        self.win.show()
    
    def handleSignup(self):
        global result
        self.result=False
        # getting Info
        name = self.name.text()
        fname = self.fname.text()
        mail = self.mail.text()
        phone = self.phone.text()
        username = self.username.text()
        password = self.pas.text()
        
        #testing info :
        if not  name.isalpha() :
            name=self.name.text()
            QMessageBox.critical(self.win,"wrong!! " ,"name should be only letters")
            
        elif not  fname.isalpha() :
            fname=self.fname.text()
            QMessageBox.critical(self.win,"wrong!! " ,"family name should be only letters")
            
        elif not  "@" in mail :
            mail=self.mail.text()
            QMessageBox.critical(self.win,"wrong!! " ,"your email is wrong")
            
        elif not (len(phone)== 8 and phone.isdigit()) :
            phone=self.phone.text()
            QMessageBox.critical(self.win,"wrong!! " ,"your phone number is wrong !!")
            
        elif username == "" :
            QMessageBox.critical(self.win,"wrong!! " ,"you have to choose a user name")
            username = self.username.text()
            
        elif   len(password) < 5 :
            passord=self.pas.text()
            QMessageBox.critical(self.win,"wrong!! " ," password should be 5 or more letters")
        
        else :
            #connecting db
            connect = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="task manager",
            )

            base = connect.cursor()
            #checking if username or mail or phone number exist exist
            base.execute("SELECT * FROM compte where username = %s",(username,))
            namesql=base.fetchall()
            
            base.execute("SELECT * FROM compte where mail = %s",(mail,))
            mailsql=base.fetchall()
            
            base.execute("SELECT * FROM compte where phone = %s",(phone,))
            phonesql=base.fetchall()
            
            if len(namesql) > 0 :
                QMessageBox.critical(self.win,"warning !!","this username already exists")
                self.result=False
            
            elif len(mailsql) > 0 :
                QMessageBox.critical(self.win,"warning !!","this email already used")
                self.result=False
            
            elif len(phonesql) > 0 :
                QMessageBox.critical(self.win,"warning !!","this phone number already used")
                self.result=False
            else :    
            
                # Inserting values in db 
                try:
                    base.execute("SELECT id FROM compte")
                    base.fetchall()
                    nb = base.rowcount + 1
                    hey=base.execute("INSERT INTO compte VALUES(%s, %s, %s, %s, %s, %s, %s)",
                                 (nb, name, fname, mail, phone, username, password))
                    connect.commit()
                    QMessageBox.information(self.win, "Success", "you singed up successfully !")
                    self.result=True 
                except mysql.connector.Error as error:
                    pirnt(str(error))
                    QMessageBox.critical(self.win, "Oops", "somthing went wrong plz try again ")
                    self.result=False
    
    def handle_signup_clicked(self):
        if self.result:
            self.openWindow(signup_2)  
    def setupUi(self, signup_2):
        global result
        self.win = signup_2
        signup_2.setObjectName("signup_2")
        signup_2.resize(892, 618)
        signup_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(signup_2)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(140, 40, 621, 521))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(250, 10, 321, 61))
        self.label_9.setMinimumSize(QtCore.QSize(321, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(30, 100, 71, 21))
        self.label_10.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_10.setObjectName("label_10")
        self.name = QtWidgets.QLineEdit(self.widget_2)
        self.name.setGeometry(QtCore.QRect(60, 120, 211, 31))
        self.name.setObjectName("name")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(320, 100, 121, 21))
        self.label_11.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_11.setObjectName("label_11")
        self.fname = QtWidgets.QLineEdit(self.widget_2)
        self.fname.setGeometry(QtCore.QRect(360, 120, 211, 31))
        self.fname.setObjectName("fname")
        self.signup = QtWidgets.QPushButton(self.widget_2)
        self.signup.setGeometry(QtCore.QRect(260, 360, 111, 51))
        self.signup.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.signup.setObjectName("signup")
        
        self.signup.clicked.connect(lambda: self.handleSignup())
        
        self.signup.clicked.connect(lambda: self.handle_signup_clicked())
        
        self.signin = QtWidgets.QPushButton(self.widget_2)
        self.signin.setGeometry(QtCore.QRect(260, 450, 111, 31))
        self.signin.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.signin.setObjectName("signin")
        
        self.signin.clicked.connect(lambda: self.openWindow(signup_2))
        
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(310, 420, 31, 21))
        self.label_12.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(30, 180, 71, 21))
        self.label_13.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(30, 260, 101, 21))
        self.label_14.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setGeometry(QtCore.QRect(320, 180, 141, 21))
        self.label_15.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setGeometry(QtCore.QRect(320, 260, 101, 21))
        self.label_16.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);")
        self.label_16.setObjectName("label_16")
        self.mail = QtWidgets.QLineEdit(self.widget_2)
        self.mail.setGeometry(QtCore.QRect(60, 200, 211, 31))
        self.mail.setObjectName("mail")
        self.username = QtWidgets.QLineEdit(self.widget_2)
        self.username.setGeometry(QtCore.QRect(60, 280, 211, 31))
        self.username.setObjectName("username")
        self.phone = QtWidgets.QLineEdit(self.widget_2)
        self.phone.setGeometry(QtCore.QRect(360, 200, 211, 31))
        self.phone.setObjectName("phone")
        self.pas = QtWidgets.QLineEdit(self.widget_2)
        self.pas.setGeometry(QtCore.QRect(360, 280, 211, 31))
        self.pas.setObjectName("pas")
        self.signin_2 = QtWidgets.QPushButton(self.widget_2)
        self.signin_2.setGeometry(QtCore.QRect(500, 480, 111, 31))
        self.signin_2.setStyleSheet("background-color: lightblue ;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: black;")
        self.signin_2.setObjectName("signin_2")
        signup_2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(signup_2)
        self.statusbar.setObjectName("statusbar")
        signup_2.setStatusBar(self.statusbar)

        self.retranslateUi(signup_2)
        self.signin_2.clicked.connect(signup_2.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(signup_2)

    def retranslateUi(self, signup_2):
        _translate = QtCore.QCoreApplication.translate
        signup_2.setWindowTitle(_translate("signup_2", "MainWindow"))
        self.label_9.setWhatsThis(_translate("signup_2", "<html><head/><body><p align=\"justify\"><span style=\" font-size:22pt;\"><br/></span></p></body></html>"))
        self.label_9.setText(_translate("signup_2", "sign up"))
        self.label_10.setText(_translate("signup_2", "name :"))
        self.label_11.setText(_translate("signup_2", "family name :"))
        self.signup.setText(_translate("signup_2", "Sign up"))
        self.signin.setText(_translate("signup_2", "Sign in"))
        self.label_12.setText(_translate("signup_2", "Or"))
        self.label_13.setText(_translate("signup_2", "Email :"))
        self.label_14.setText(_translate("signup_2", "username :"))
        self.label_15.setText(_translate("signup_2", "Phone number :"))
        self.label_16.setText(_translate("signup_2", "password :"))
        self.signin_2.setText(_translate("signup_2", "Close"))
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signup_2 = QtWidgets.QMainWindow()
    ui = Ui_signup_2()
    ui.setupUi(signup_2)
    signup_2.show()
    sys.exit(app.exec_())
